"""student account invite codes for CSV class import

Revision ID: b9c0d1e2f3a4
Revises: f7a8b9c0d1e2
Create Date: 2026-09-06

S2.2: student_invites stores only SHA-256 hashes of one-time claim codes
generated by the teacher CSV bulk-import endpoint. No backfill (new feature).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b9c0d1e2f3a4"
down_revision: str | Sequence[str] | None = "f7a8b9c0d1e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "student_invites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("classroom_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["classroom_id"], ["classrooms.id"]),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_student_invites_code_hash"), "student_invites", ["code_hash"], unique=True)
    op.create_index(op.f("ix_student_invites_email"), "student_invites", ["email"], unique=False)
    op.create_index(
        op.f("ix_student_invites_classroom_id"), "student_invites", ["classroom_id"], unique=False
    )
    op.create_index(
        op.f("ix_student_invites_student_id"), "student_invites", ["student_id"], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_student_invites_student_id"), table_name="student_invites")
    op.drop_index(op.f("ix_student_invites_classroom_id"), table_name="student_invites")
    op.drop_index(op.f("ix_student_invites_email"), table_name="student_invites")
    op.drop_index(op.f("ix_student_invites_code_hash"), table_name="student_invites")
    op.drop_table("student_invites")
